### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by jack9603301** [Helicone/helicone#2247]
I encountered a tricky problem when deploying the service. The deployment was completely based on the description of https://docs.helicone.ai/getting-started/self-deploy

. However, I was unable to log in. It always prompted that the login was successful, but when it jumped, it always prompted:

```
signin.tsx:35 Error: Loading initial props cancelled
    at eval (router.js:1383:29)
    at async Router.getRouteInfo (router.js:1112:41)
    at async Router.change (router.js:698:29)
console.error @ client.js:26
window.console.error @ setup-hydration-warning.js:18
handleRouteInfoError @ router.js:936
getRouteInfo @ router.js:1171
await in getRouteInfo（异步）
change @ router.js:698
await in change（异步）
push @ router.js:423
instance.<computed> @ router.js:174
SignIn @ signin.tsx:35
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19583
beginWork @ react-dom.development.js:21596
beginWork$1 @ react-dom.development.js:27421
performUnitOfWork @ react-dom.development.js:26552
workLoopConcurrent @ react-dom.development.js:26538
renderRootConcurrent @ react-dom.development.js:26500
performConcurrentWorkOnRoot @ react-dom.development.js:25733
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
显示另外 18 个框架
收起
signin.tsx:58 Error: Loading initial props cancelled
    at eval (router.js:1383:29)
    at async Router.getRouteInfo (router.js:1112:41)
    at async Router.change (router.js:698:29)
console.error @ client.js:26
window.console.error @ setup-hydration-warning.js:18
handleRouteInfoError @ router.js:936
getRouteInfo @ router.js:1171
await in getRouteInfo（异步）
change @ router.js:698
await in change（异步）
push @ router.js:423
instance.<computed> @ router.js:174
handleEmailSubmit @ signin.tsx:58
await in handleEmailSubmit（异步）
handleEmailSubmitHandler @ authForm.tsx:51
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26135
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
显示另外 22 个框架
收起
signin.tsx:35 Error: Loading initial props cancelled
    at eval (router.js:1383:29)
    at async Router.getRouteInfo (router.js:1112:41)
    at async Router.change (router.js:698:29)
console.error @ client.js:26
window.console.error @ setup-hydration-warning.js:18
handleRouteInfoError @ router.js:936
getRouteInfo @ router.js:1171
await in getRouteInfo（异步）
change @ router.js:698
await in change（异步）
change @ router.js:775
await in change（异步）
change @ router.js:775
await in change（异步）
push @ router.js:423
instance.<computed> @ router.js:174
SignIn @ signin.tsx:35
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19583
beginWork @ react-dom.development.js:21596
beginWork$1 @ react-dom.development.js:27421
performUnitOfWork @ react-dom.development.js:26552
workLoopConcurrent @ react-dom.development.js:26538
renderRootConcurrent @ react-dom.development.js:26500
performConcurrentWorkOnRoot @ react-dom.development.js:25733
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
显示另外 20 个框架
收起
signin.tsx:35 Error: Loading initial props cancelled
    at eval (router.js:1383:29)
    at async Router.getRouteInfo (router.js:1112:41)
    at async Router.change (router.js:698:29)
console.error @ client.js:26
window.console.error @ setup-hydration-warning.js:18
handleRouteInfoError @ router.js:936
getRouteInfo @ router.js:1171
await in getRouteInfo（异步）
change @ router.js:698
await in change（异步）
push @ router.js:423
instance.<computed> @ router.js:174
SignIn @ signin.tsx:35
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19583
beginWork @ react-dom.development.js:21596
beginWork$1 @ react-dom.development.js:27421
performUnitOfWork @ react-dom.development.js:26552
workLoopConcurrent @ react-dom.development.js:26538
renderRootConcurrent @ react-dom.development.js:26500
performConcurrentWorkOnRoot @ react-dom.development.js:25733
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
显示另外 18 个框架
收起
```

![image](https://github.com/Helicone/helicone/assets/9047180/1659bfbe-b046-481a-995c-a3fada5ed7b6)
![image](https://github.com/Helicone/helicone/assets/9047180/7e7d6b2e-f7c4-4870-b223-6c495f4e1c91)

**Comment by chitalian** [comment]
Hi @jack9603301 can you share your .env file in `/valhalla/jawn`?

It should look something like this

```
SUPABASE_CREDS={"url": "http://localhost:54321", "service_role_key": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU" }
SUPABASE_DATABASE_URL="postgresql://postgres:postgres@localhost:54322/postgres"
S3_ACCESS_KEY="minioadmin"
S3_SECRET_KEY="minioadmin"
S3_ENDPOINT="http://localhost:9000"
S3_BUCKET_NAME="request-response-storage"
HELICONE_WORKER_URL="http://localhost:8787"
```

You might have better luck following the docs here: https://github.com/Helicone/helicone/tree/main


If this doesnt work for you and you just want helicone working locally. I would recommend running `docker compose up` in the docker directory

https://docs.helicone.ai/getting-started/self-deploy-docker

**Comment by jack9603301** [comment]
Sorry, since the customer undeployed the component, I can't provide the configuration, and I don't need to provide the configuration, I can only tell you that I used a configuration similar to the one provided by your readme.

**Comment by jack9603301** [comment]
Sorry, since the customer undeployed the component, I can't provide the configuration, and I don't need to provide the configuration, I can only tell you that I used a configuration similar to the one provided by your readme.
