### ISSUE TITLE
WORKER_MAP[provider] is not a function

### ISSUE THREAD

**Issue by jmikedupont2** [Helicone/helicone#852]
````
TypeError: WORKER_MAP[provider] is not a function
    at buildRouter (file:///tmp/tmp-1740376-vHihdX2PaXlj/index.js:63726:23)                                                   at Object.fetch (file:///tmp/tmp-1740376-vHihdX2PaXlj/index.js:63887:22)
    at async jsonError (file:///tmp/tmp-1740376-vHihdX2PaXlj/index.js:63963:12) {                                           stack: TypeError: WORKER_MAP[provider] is not a function                                                                …//tmp/tmp-1740376-vHihdX2PaXlj/index.js:63963:12),                                                                         message: WORKER_MAP[provider] is not a function

````
from this test 
```
curl --request POST \
  --url http://localhost:8788/custom/v1/log \
  --header 'Authorization: Bearer sk-helicone-aizk36y-5yue2my-qmy5tza-n7x3aqa' \
  --header 'Content-Type: application/json' \
  --data '{
    "providerRequest": {
        "url": "apple.com",
        "json": {
            "model": "gpt-3",
            "prompt": "Hello all"
        },
        "meta": {
            "Helicone-User-Id": "ligma",
            "Helicone-Property-hi": "by"
        }
    },
    "providerResponse": {
        "json": {
            "id": "cmpl-7VUOT5k59aStnqxxXJwtyGnZibv1e",
            "model": "llama-2",
            "usage": {
                "total_tokens": 16,
                "prompt_tokens": 14,
                "completion_tokens": 2
            },
            "object": "text_completion",
            "choices": [
                {
                    "text": "\nHello",
                    "index": 0,
                    "logprobs": null,
                    "finish_reason": "length"
                }
            ],
            "created": 1687739357
        },
        "status": 200,
        "headers": {
            "openai-version": "ligmaligma"
        }
    },
    "timing": {
        "startTime": {
            "seconds": 1694381565,
            "milliseconds": 763
        },
        "endTime": {
            "seconds": 1694381575,
            "milliseconds": 321
        }
    }
}'
```

**Comment by chitalian** [comment]
Hi @jmikedupont2 Are you still experiencing this issue?

**Comment by jmikedupont2** [comment]
thats why i reported it

**Comment by fauh45** [comment]
Hi @jmikedupont2 not really a maintainer, but have you check for `WORKER_TYPE` in your env? It should have value either "OPENAI_PROXY" or "ANTHROPIC_PROXY" or "HELICONE_API". At least that's what I found when poking around Helicone.

**Comment by chitalian** [comment]
Hi @jmikedupont2, as @fauh45 said you have to specify a worker type.

You can see some documentation on this here:
https://docs.helicone.ai/getting-started/self-deploy

`wrangler dev --local --var WORKER_TYPE:OPENAI_PROXY --port 8787`

**Comment by jmikedupont2** [comment]
Ok I will circle back to this soon.
